### ISSUE TITLE
Finalization of Videos/Academic Integrity.

### ISSUE THREAD

**Issue by icyasher** [btanti/aspen-tutorials#20]
Make sure we give credit to the papers and sources we used.

Go over audio/videos and decide what fixes are deemed necessary and feasible (Audio fixes easier to incorporate).

Edit descriptions and scripts for subtitles.

**Comment by btanti** [comment]
Exercises involving PSD mesh data, adapted from Chemical Process Design and Simulation: Aspen Plus and Aspen Hysys Applications
